import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteHeader } from '@/components/SiteHeader';
import { SiteFooter } from '@/components/SiteFooter';

export const metadata: Metadata = {
  title: 'Terms of Service | Contract Checked',
  description: 'Terms of Service for Contract Checked — read before using our AI-powered contract analysis platform.',
  alternates: {
    canonical: 'https://contractchecked.com/terms',
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#F9FAFB]">
      <SiteHeader />

      {/* Hero */}
      <section className="bg-[#1C2333] text-white pt-16 pb-12">
        <div className="max-w-3xl mx-auto px-4">
          <h1 className="text-4xl font-extrabold tracking-tight mb-3">Terms of Service</h1>
          <p className="text-slate-400 text-sm">Last updated: April 18, 2026</p>
        </div>
      </section>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-12 space-y-10">

        {/* NOT LEGAL ADVICE — most important section, shown first */}
        <div className="bg-amber-50 border-2 border-amber-400 rounded-xl p-6">
          <h2 className="text-xl font-bold text-amber-900 mb-3">⚠️ Important: Not Legal Advice</h2>
          <p className="text-amber-900 text-sm leading-relaxed">
            <strong>Contract Checked is an informational tool, not a law firm, and does not provide legal advice.</strong> The analysis, summaries, risk assessments, and any other output generated by Contract Checked are for informational and educational purposes only. Nothing on this platform should be construed as legal advice, legal opinion, or a recommendation to take or refrain from any legal action.
          </p>
          <p className="text-amber-900 text-sm leading-relaxed mt-3">
            <strong>Always consult a qualified attorney licensed in your jurisdiction before signing any legally binding contract or making any legal decision.</strong> The consequences of a contract can be significant — AI analysis cannot substitute for professional legal counsel.
          </p>
        </div>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">1. Acceptance of Terms</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>By accessing or using Contract Checked (&quot;the Service&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.</p>
            <p>These Terms constitute a legally binding agreement between you and Contract Checked. We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">2. Description of Service</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>Contract Checked is an AI-powered contract analysis platform that helps users understand contracts they are considering signing. The Service provides:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-generated analysis of uploaded contract documents</li>
              <li>Plain-English summaries of contract clauses</li>
              <li>Identification of potential risks, red flags, and missing clauses</li>
              <li>Contract comparison tools</li>
              <li>Contract template downloads</li>
              <li>Educational guides about common contract types</li>
            </ul>
            <p>Core analysis features are provided free of charge. No account is required for basic use.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">3. Not Legal Advice</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p><strong>This section is critical and governs the entire relationship between you and Contract Checked.</strong></p>
            <p>Contract Checked does not practice law and does not provide legal advice. The output of the Service — including all analysis, summaries, risk scores, flags, recommendations, and template documents — is:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generated by AI and may contain errors, omissions, or inaccuracies</li>
              <li>Not reviewed by a licensed attorney before being delivered to you</li>
              <li>Not tailored to your specific legal situation, jurisdiction, or circumstances</li>
              <li>Not a substitute for professional legal counsel</li>
              <li>Not guaranteed to be complete, accurate, or current with applicable law</li>
            </ul>
            <p><strong>Do not rely on Contract Checked&apos;s output as your sole basis for signing, rejecting, or negotiating any contract.</strong> Laws vary by jurisdiction and change over time. The analysis provided may not reflect current law in your location.</p>
            <p>If you have questions about a contract&apos;s legal effect, enforceability, or implications for your situation, consult a licensed attorney.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">4. Acceptable Use</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>You agree to use Contract Checked only for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Upload content that is illegal, fraudulent, or that you do not have the right to share</li>
              <li>Use the Service to analyze contracts for the purpose of engaging in fraud, forgery, or any illegal activity</li>
              <li>Attempt to circumvent, disable, or interfere with security features of the Service</li>
              <li>Scrape, crawl, or systematically extract data from the Service using automated tools</li>
              <li>Use the Service in a manner that could damage, disable, overburden, or impair our servers or networks</li>
              <li>Impersonate any person or entity or falsely represent your affiliation with any person or entity</li>
              <li>Upload content that infringes any third party&apos;s intellectual property rights or other legal rights</li>
              <li>Attempt to gain unauthorized access to any part of the Service or its underlying systems</li>
            </ul>
            <p>We reserve the right to terminate access for users who violate these terms.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">5. Intellectual Property</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p><strong>Your contracts:</strong> You retain full ownership of any contracts or documents you upload. By uploading, you grant us a limited, temporary license to process the content solely to provide you with analysis results. This license ends when your session ends.</p>
            <p><strong>Our platform:</strong> Contract Checked, including its design, code, analysis algorithms, educational content, templates, and branding, is owned by Contract Checked and protected by intellectual property laws. You may not copy, reproduce, distribute, or create derivative works from our platform without explicit written permission.</p>
            <p><strong>Analysis output:</strong> The analysis results generated by the Service are provided to you for personal, non-commercial use. You may not resell or commercially redistribute analysis output.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">6. Disclaimer of Warranties</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OR NON-INFRINGEMENT.</p>
            <p>We do not warrant that:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>The Service will be uninterrupted, error-free, or available at any particular time</li>
              <li>The analysis results will be accurate, complete, or suitable for your purposes</li>
              <li>Any defects in the Service will be corrected</li>
              <li>The Service is free from viruses or other harmful components</li>
            </ul>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">7. Limitation of Liability</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CONTRACT CHECKED SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.</p>
            <p>IN NO EVENT SHALL CONTRACT CHECKED&apos;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE EXCEED THE GREATER OF: (A) $100 CAD, OR (B) THE TOTAL AMOUNT PAID BY YOU TO CONTRACT CHECKED IN THE 12 MONTHS PRECEDING THE CLAIM.</p>
            <p>Some jurisdictions do not allow the exclusion or limitation of certain warranties or liabilities, so some of the above limitations may not apply to you.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">8. Indemnification</h2>
          <div className="text-slate-600 text-sm leading-relaxed">
            <p>You agree to indemnify, defend, and hold harmless Contract Checked and its affiliates, officers, employees, and agents from any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or in connection with: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any content you upload to the Service.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">9. Governing Law</h2>
          <div className="text-slate-600 text-sm leading-relaxed">
            <p>These Terms shall be governed by and construed in accordance with the laws of the Province of Ontario, Canada, without regard to its conflict of law provisions. You agree that any legal action or proceeding relating to these Terms or the Service shall be brought exclusively in the courts of Ontario, Canada, and you consent to the jurisdiction of such courts.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">10. Dispute Resolution</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>Before filing any formal legal claim, you agree to first contact us at <a href="mailto:support@contractchecked.com" className="text-[#2D6A4F] underline">support@contractchecked.com</a> and attempt to resolve the dispute informally. We will make reasonable efforts to resolve disputes within 30 days of receiving written notice.</p>
            <p>If informal resolution fails, disputes shall be resolved through binding arbitration in Ontario, Canada, in accordance with applicable arbitration rules, except that either party may seek injunctive or other equitable relief in court for claims involving intellectual property rights or violations of acceptable use policies.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">11. Termination</h2>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3">
            <p>We reserve the right to terminate or suspend your access to the Service at any time, with or without notice, for any reason, including if we believe you have violated these Terms.</p>
            <p>You may stop using the Service at any time. If you have created an account, you may request account deletion by emailing <a href="mailto:support@contractchecked.com" className="text-[#2D6A4F] underline">support@contractchecked.com</a>.</p>
            <p>Upon termination, all provisions of these Terms that by their nature should survive will survive, including intellectual property provisions, warranty disclaimers, indemnity, and limitations of liability.</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-800 mb-4">12. Contact</h2>
          <div className="text-slate-600 text-sm leading-relaxed">
            <p>For questions about these Terms, contact us at:</p>
            <div className="bg-white border border-slate-200 rounded-xl p-4 mt-3">
              <p className="font-semibold text-slate-800">Contract Checked</p>
              <p>Email: <a href="mailto:support@contractchecked.com" className="text-[#2D6A4F] underline">support@contractchecked.com</a></p>
            </div>
          </div>
        </section>

        <div className="border-t border-slate-200 pt-8 flex flex-wrap gap-4 text-sm">
          <Link href="/privacy" className="text-[#2D6A4F] hover:underline">Privacy Policy</Link>
          <Link href="/about" className="text-[#2D6A4F] hover:underline">About Contract Checked</Link>
          <Link href="/" className="text-[#2D6A4F] hover:underline">Back to Home</Link>
        </div>

      </div>

      <SiteFooter />
    </div>
  );
}
